export const ACTIONS = {

    // CART ACTIONS
    ADD_TO_CART: "ADD_TO_CART",
    DELETE_FROM_CART: "DELETE_FROM_CART",
    CLEAR_CART: "CLEAR_CART",

    // DB ACTIONS
    DELETE_FROM_DB: "DELETE_FROM_DB",
    EDIT_PRODUCT_FROM_DB: "EDIT_PRODUCT_FROM_DB"
}